### ISSUE TITLE
Is dxl_hal.c still needed with DynamixelSDK?

### ISSUE THREAD

**Issue by abencomo** [Xevel/usb2ax#2]
I'm not able to find the dxl_hal.c file in the [DynamixelSDK](https://github.com/ROBOTIS-GIT/DynamixelSDK) repository, is it still needed or used?

**Comment by Xevel** [comment]
They updated the DynamixelSDK to version 3 and my files were for previous versions of the library. I haven't tried using the new one yet, but it looks significantly different.
