### ISSUE TITLE
Handle dynamixel protocol 2 ...

### ISSUE THREAD

**Issue by tho-** [Xevel/usb2ax#4]
Hi,

I flashed the latest firmware available in the repo ( USB2AX_v05RC0.hex ) on a USB2AX v3.2a.
I'm communicating with MX and XM motors that talk protocol 2.

The problem is that all messages, that start by construction with 0xff 0xff 0xfd 0x0, are interpreted by the USB2AX as (bad) messages for itself with a 0 length. So it passes the message to the MX motor (ok), but then replies on the usb with a protocol 1 error message which does not make sense here.

Would there be a way to disable this interpretation of dynamixel protocol? Or recognize protol 2 messages (starting with 0xff ff fd 00) as such and not reply with an error?

**Comment by Xevel** [comment]
Hi,

Could you put the old (v04) firmware back please?
I'll need some time to get to this, can't do it right away.

You cab download it here: http://www.xevelabs.com/doku.php?id=product:usb2ax:firmware

Best
Nicolas

**Comment by tho-** [comment]
On Wednesday 26 Jul 2017, at 18:32, Nicolas SAUGNIER wrote:
> Could you put the old (v04) firmware back please?
> I'll need some time to get to this, can't do it right away.

No, the old firmware is not usable for me. I need to transmit large
messages, (around 128 bytes x 2 motors or even 3), and I had a lot of
message corruption with the v04 firmware. (while the exact same setup
runs fine with the USBtoDynamixel device).

That's why I upgraded. The increased buffer size in the latest version
helps a lot. (although I still experience a few message corruption
from time to time).

I understand perfectly that you cannot work on this immediately.
The short-term fix I have in mind is just a couple of lines long. If I
suggest a patch, maybe you could just apply it and build a new image
in a few minutes?

I wish I could compile the code myself. But when I tried, I could not
produce a useable software. I don't have AVR Studio, so I compiled
everything manually with avr-gcc (on linux), but for some reason the
hex file I obtain is about ~40kB large (instead of the ~17kB file in
the repository) and hangs the device when it is flashed. I tried to
put the same avr-gcc options as in the .cproj file (-Os, -gc-sections,
etc.), but I could not understand why it's not working yet.

**Comment by Xevel** [comment]
Hmm, seems like there is definitely a big problem on my side, sorry about that.

If you have a fix I can compile it for you, sure.

For your problem with avr-gcc, seems to me like link-time issues, where some "standard" libs are automatically added by AVR studio.

Just out of curiosity, what is your application where you need to send messages that long - it you can share ?

**Comment by tho-** [comment]
On Wednesday 26 Jul 2017, at 21:11, Nicolas SAUGNIER wrote:
> Hmm, seems like there is definitely a big problem on my side, sorry
> about that.
>
> If you have a fix I can compile it for you, sure.

I attach a diff which should do the trick. (untested, however).
Comments in the code should explain what I'm doing, but if you have
any doubt we can discuss about it.

> For your problem with avr-gcc, seems to me like link-time issues,
> where some "standard" libs are automatically added by AVR studio.

If AVR studio ever displays the actual compile command line, I'd be
curious to compare with what I'm doing.

> Just out of curiosity, what is your application where you need to
> send messages that long - it you can share ?

To be exact, I need to receive such messages, not to send them. When
configuring the motors, I use a protocol 2.0 SYNC_READ message to
retrieve a great part of the control table of all connected devices.

It's true that I could split this into several smaller messages. It's
doable if nothing else works, but since I saw the commits here, fixing
the buffer issue, I wanted to give it a try first (and I was not sure
until after trying that the message size was the issue).

The other issue that I'm trying to address in the attached patch seems
to be only remaining one, so I'd say it's worth trying to get rid of
it :) But if you think that v04 would work better with small
protocol 2.0 messages, then I could try to do that instead.

My code is freely available, although of little interest to share
because it uses a custom integration framework (also free, but complex
to get into). All this is part of research projects using multirotor
drones equipped with manipulator arms.
You can get an idea there:
http://homepages.laas.fr/afranchi/robotics/?q=node/416
The actual motor code can be seen here:
https://git.openrobots.org/projects/dynamixel-genom3/repository


diff --git firmware/lufa_usb2ax/USB2AX.c firmware/lufa_usb2ax/USB2AX.c
index 8692398..22f8e40 100644
--- firmware/lufa_usb2ax/USB2AX.c
+++ firmware/lufa_usb2ax/USB2AX.c
@@ -293,8 +293,13 @@ void process_incoming_USB_data(void){
                             
                 case AX_SEARCH_LENGTH:
                     rxbyte[rxbyte_count++] = CDC_Device_ReceiveByte(&USB2AX_CDC_Interface);
-                    if (rxbyte[PACKET_ID] == AX_ID_DEVICE || rxbyte[PACKET_ID] == AX_ID_BROADCAST ){
-                        if (rxbyte[PACKET_LENGTH] > 1 && rxbyte[PACKET_LENGTH] < (AX_SYNC_READ_MAX_DEVICES + 4)){  // reject message if too short or too big for rxbyte buffer
+                    if (rxbyte[PACKET_ID] == 0xFD && (rxbyte[PACKET_LENGTH] == 0 || rxbyte[PACKET_LENGTH] == 0xFD)) {
+                        // We've seen 0xFF 0xFF 0xFD 0x0 or 0xFF 0xFF 0xFD 0xFD
+                        // Both are protocol 2.0 messages (header or "byte stuffing")
+                        // Let this pass - both are invalid for us anyway
+                        cleanup_input_parser();
+                    } else if (rxbyte[PACKET_ID] == AX_ID_DEVICE || rxbyte[PACKET_ID] == AX_ID_BROADCAST ){
+                         if (rxbyte[PACKET_LENGTH] > 1 && rxbyte[PACKET_LENGTH] < (AX_SYNC_READ_MAX_DEVICES + 4)){  // reject message if too short or too big for rxbyte buffer
                             ax_state = AX_SEARCH_COMMAND;
                             receive_timer = 0;
                         } else {

**Comment by Xevel** [comment]
Hi,

So I had a better look... and sure enough stuff is all f**** up when using DXL2.0 with the latest version of Dynamixel Wizard, and I guess the fact that it worked in other cases was just down to implementation details (a lib that would match 1-1 packets would never receive the answer to sync_read_2.0, whereas one that processes packet as they come might...).

So I applied your patch, and things look better now.
I uploaded the binary of v05 RC1, please tell me if it fixed your problem.
Also so far I credited you with your github handle, let me know if you prefer your real name.

Find here the full output of the build : https://pastebin.com/QhbBByLH

And that's pretty cool stuff you're working on :D Have fun!

**Comment by tho-** [comment]
On Wednesday 26 Jul 2017, at 22:47, Nicolas SAUGNIER wrote:
> So I applied your patch, and things look better now.  I uploaded the
> binary of v05 RC1, please tell me if it fixed your problem.

Yes. I just did a quick test, but it already shows much better
results.
Thanks Nicolas for the promptness!


> Also so far I credited you with your github handle, let me know if
> you prefer your real name.

I'm Anthony Mallet outside github, which might be a more reliable
name than my github handle :) But don't bother with this, I don't care
so much :)

> Find here the full output of the build :
> https://pastebin.com/QhbBByLH

Thanks, I will check. If I later manage to build it for linux, I might
submit a Makefile or something, to add in the repo, if you like.
