### ISSUE TITLE
Upgrading to the latest DynamixelSDK?

### ISSUE THREAD

**Issue by vikashplus** [Xevel/usb2ax#5]
Hi, 

I'm trying to use USB2AX with the latest version of the [Dynamixel SDK](https://github.com/ROBOTIS-GIT/DynamixelSDK). Are there any plans on upgrading this repo to work with the latest SDK?

**Comment by Xevel** [comment]
Hi,
I think some people did it on the Trossen Robotics Forums, and it was relatively painless. You should have a look there.
Aside from this, I currently have no plan to work on the DynamixelSDK again.

**Comment by vikashplus** [comment]
Thanks, I got to work fairly easily. The old documentation isn't relevant anymore. It throws you on the wrong path. Its easier to do it with a fresh mind without reading the old doc in this repo.

Thanks for the great product. My initial experience is quite good so far

**Comment by Xevel** [comment]
Thanks for the feedback. I'll make it clearer that the current doc is not relevant anymore.
Cheers.
